name: Build with Maven and Do Runtime Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
        
    - name: Maven Build
      run: mvn clean package --file pom.xml
      
    - name: Upload the artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ github.event.number }}
        path: 'target/*.jar'

    - name: 自动释放
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "jar"
        prerelease: true
        title: "FNAmplifications 自动构建版本"
        files: |
          target/*

  create_release:
    name: "创建发布"
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
    - name: 下载构建
      uses: actions/download-artifact@v4.1.7
        
    - name: 创建发布
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: |
          artifacts/*

  runtime-test:
    name: Plugin Runtime Test 
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mcVersion: '1.17.1'
            javaVersion: '17'
          - mcVersion: '1.18.2'
            javaVersion: '18'
          - mcVersion: '1.19.4'
            javaVersion: '19'
          - mcVersion: '1.20.1'
            javaVersion: '20'
          - mcVersion: '1.20.6'
            javaVersion: '21'
          - mcVersion: '1.21.1'
            javaVersion: '22'
          - mcVersion: '1.20.4'
            javaVersion: '21'  
          - mcVersion: '1.21'
            javaVersion: '21'  
    
    steps:        
      - uses: buiawpkgew1/minecraft-plugin-runtime-test@v1.1.6
        with:
          server-version: ${{ matrix.mcVersion }}
          java-version: ${{ matrix.javaVersion }}
          artifact-name: artifact-${{ github.event.number }}
