name: Build with maven

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*"
  pull_request:
    branches:
      - main
    
jobs:
  create_release:
    name: "创建发布"
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
    - name: 下载构建
      uses: actions/download-artifact@v3.0.2
        
    - name: 创建发布
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: |
          artifacts/*
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.3
      
    - name: Set up JDK 16
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 16
        
    - name: Maven Build
      run: mvn package --file pom.xml
    - name: 自动释放
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "jar"
        prerelease: true
        title: "FNAmplifications 自动构建版本"
        files: |
           target/*
    - name: 上传 The Bruh
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
           target/*.jar
